site_name: SpencerDevv Site
site_url: https://internalrblx.github.io/SpencerDevv-Website/

extra:
  version:
    provider: mike

theme:
  icon:
    logo: material/database
    repo: fontawesome/brands/git-alt
  name: material
  favicon: docs/images/favicon.png
  palette:
    - scheme: default
      primary: Blue
      accent: Blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: Dark Blue
      accent: Dark Blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Home: index.md
  - HeroClash DevLogs:
    - About HeroClash: DevLogs/AboutHeroClash.md
    - Log 01: DevLogs/Log01.md
    - Log 02: DevLogs/Log02.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences